### ISSUE TITLE
Homebridge Docker not working 'functions-have-names'

### ISSUE THREAD

**Issue by stoffLer** [homebridge/docker-homebridge#521]
### Analysis

[9/13/2023, 12:50:10 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/13/2023, 12:50:15 PM] [HB Supervisor] Restarting Homebridge...
[9/13/2023, 12:50:15 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[9/13/2023, 12:50:15 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 5839
Error: Cannot find module 'functions-have-names'
Require stack:
- /opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/implementation.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/deep-equal/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/helpers.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Server.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/AccessoryLoader.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/index.js
- /opt/homebridge/lib/node_modules/homebridge/lib/cli.js
- /opt/homebridge/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
[9/13/2023, 12:50:16 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null

### Expected Behavior

running HB...

### Steps To Reproduce

Install Docker Version of HB 

### Logs

```markdown
[9/13/2023, 12:50:10 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/13/2023, 12:50:15 PM] [HB Supervisor] Restarting Homebridge...
[9/13/2023, 12:50:15 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[9/13/2023, 12:50:15 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 5839
Error: Cannot find module 'functions-have-names'
Require stack:
- /opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/implementation.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/deep-equal/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/helpers.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Server.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/AccessoryLoader.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/index.js
- /opt/homebridge/lib/node_modules/homebridge/lib/cli.js
- /opt/homebridge/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
[9/13/2023, 12:50:16 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
```

### Configuration

```json
stock
```

### Environment

- OS: Docker on Ubuntu
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by zanedasavage** [comment]
npm install functions-have-names

This finally worked for me on a qnap container (docker)

Thank you for the tip

**Comment by BOB-DK** [comment]
> @BOB-DK are you executing that within the container, and not the host? It should work as a temporary fix.

I actually don't know.
I open Terminal via the Homebridge UI
Type the command, npm install functions-have-names

![2023-09-13 kl  16 19 23](https://github.com/homebridge/docker-homebridge/assets/95053699/90817a46-cb44-422c-b078-2c3a8a0cb6ec)

**Comment by stoffLer** [comment]
@BOB-DK what's the exact error message hb gives u?

**Comment by NorthernMan54** [comment]
@stoffLer Something looks odd with your docker-homebridge image

In the docker-homebridge image, the homebridge package gets installed into `/var/lib/homebridge/node_modules/homebridge` and not `/opt/homebridge/lib/node_modules/homebridge`.

**Comment by BOB-DK** [comment]
@stoffLer 

This is from my HB log.

[14/09/2023, 16:35:02] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[14/09/2023, 16:35:07] [HB Supervisor] Restarting Homebridge...
[14/09/2023, 16:35:07] [HB Supervisor] Starting Homebridge with extra flags: -I
[14/09/2023, 16:35:07] [HB Supervisor] Started Homebridge v1.6.1 with PID: 18597
Error: Cannot find module 'functions-have-names'
Require stack:
- /usr/local/lib/node_modules/homebridge/node_modules/set-function-name/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/implementation.js
- /usr/local/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/deep-equal/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/helpers.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Server.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/AccessoryLoader.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/set-function-name/index.js:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
